# Generated by Django 4.2 on 2026-02-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_buyer_listing_is_featured_listingview_boost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='listing',
            name='extra_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
