# Generated by Django 4.2 on 2026-02-17 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_alter_conversation_options_message_guest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='guest_phone',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
