import { AnnonceCard } from '@/types';

export const PLACEHOLDER_ANNONCES: AnnonceCard[] = [
    {
        id: '1',
        slug: 'iphone-15-pro-max-titanium',
        title: 'iPhone 15 Pro Max Titanium - Neuf Scellé',
        price: 950000,
        price_negotiable: true,
        city: 'Douala',
        region: 'Littoral',
        cover_image: '/images/placeholders/iphone.png',
        created_at: new Date().toISOString(),
        is_urgent: true,
        is_featured: true,
        category: { id: 'tech', name: 'Informatique & Tech', slug: 'informatique-tech' },
        user: { id: 'u1', full_name: 'Junior Teko', avatar_url: null, is_verified: true },
        views_count: 124,
        favorites_count: 12,
        etat: 'NEUF' as any,
        statut: 'ACTIVE' as any,
    },
    {
        id: '2',
        slug: 'toyota-land-cruiser-300-2024',
        title: 'Toyota Land Cruiser 300 VXR - 2024',
        price: 85000000,
        price_negotiable: false,
        city: 'Yaoundé',
        region: 'Centre',
        cover_image: '/images/placeholders/car.png',
        created_at: new Date(Date.now() - 3600000).toISOString(),
        is_urgent: false,
        is_featured: true,
        category: { id: 'auto', name: 'Véhicules', slug: 'vehicules' },
        user: { id: 'u2', full_name: 'Elite Motors', avatar_url: null, is_verified: true },
        views_count: 540,
        favorites_count: 45,
        etat: 'NEUF' as any,
        statut: 'ACTIVE' as any,
    },
    {
        id: '3',
        slug: 'macbook-pro-m3-max-14',
        title: 'MacBook Pro M3 Max 14" - 32GB RAM / 1TB',
        price: 2100000,
        price_negotiable: true,
        city: 'Douala',
        region: 'Littoral',
        cover_image: '/images/placeholders/macbook.png',
        created_at: new Date(Date.now() - 7200000).toISOString(),
        is_urgent: true,
        is_featured: false,
        category: { id: 'tech', name: 'Informatique & Tech', slug: 'informatique-tech' },
        user: { id: 'u1', full_name: 'Junior Teko', avatar_url: null, is_verified: true },
        views_count: 89,
        favorites_count: 5,
        etat: 'NEUF' as any,
        statut: 'ACTIVE' as any,
    },
    {
        id: '4',
        slug: 'appartement-haut-standing-bastos',
        title: 'Appartement Haut Standing meublé - Bastos',
        price: 75000,
        price_negotiable: true,
        city: 'Yaoundé',
        region: 'Centre',
        cover_image: '/images/placeholders/apartment.png',
        created_at: new Date(Date.now() - 86400000).toISOString(),
        is_urgent: false,
        is_featured: true,
        category: { id: 'immo', name: 'Immobilier', slug: 'immobilier' },
        user: { id: 'u3', full_name: 'Bastos Rentals', avatar_url: null, is_verified: false },
        views_count: 1200,
        favorites_count: 88,
        etat: 'BON_ETAT' as any,
        statut: 'ACTIVE' as any,
    },
    {
        id: '5',
        slug: 'nike-air-jordan-1-retro',
        title: 'Nike Air Jordan 1 Retro High - Édition limitée',
        price: 120000,
        price_negotiable: false,
        city: 'Douala',
        region: 'Littoral',
        cover_image: '/images/placeholders/sneakers.png',
        created_at: new Date(Date.now() - 172800000).toISOString(),
        is_urgent: false,
        is_featured: false,
        category: { id: 'fashion', name: 'Mode & Beauté', slug: 'mode-beaute' },
        user: { id: 'u4', full_name: 'Sneakers Paradise', avatar_url: null, is_verified: true },
        views_count: 450,
        favorites_count: 32,
        etat: 'NEUF' as any,
        statut: 'ACTIVE' as any,
    }
];
