# Generated by Django 4.2 on 2026-02-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_sms',
            field=models.BooleanField(default=False),
        ),
    ]
