# Generated by Django 4.2 on 2026-02-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_notification_email_profile_notification_push_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
