# Generated by Django 4.2 on 2026-02-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Chez-BEN2', max_length=100)),
                ('contact_email', models.EmailField(default='contact@chez-ben2.com', max_length=254)),
                ('contact_phone', models.CharField(default='+237 600 000 000', max_length=20)),
                ('address', models.TextField(default='Douala, Cameroun')),
                ('credit_price_xaf', models.DecimalField(decimal_places=0, default=100, max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Paramètres',
                'verbose_name_plural': 'Paramètres',
            },
        ),
    ]
